services:
  logwatcher.app:
    image: logwatcher.app
    build:
      context: .
      dockerfile: LogWatcher.App/Dockerfile
    command:
      - ./../data  # assuming /app is the working directory in the container
    volumes:
      - ./temp:/data  # Mount host ./temp to container /data

  logwatcher.seeder:
    depends_on:
      - logwatcher.app
    image: logwatcher.seeder
    build:
      context: .
      dockerfile: LogWatcher.Seeder/Dockerfile
    volumes:
      - ./temp:/data
      - ./LogWatcher.Seeder/appsettings.compose.json:/app/appsettings.json:ro  # Read-only mount for config file
